"""add_scan_sessions

Revision ID: 0423465a6a03
Revises: 001
Create Date: 2026-07-06 15:36:08.254733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0423465a6a03'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    op.create_table('scan_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kiosk_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('color_mode', postgresql.ENUM('nb', 'couleur', name='color_mode', create_type=False), nullable=False),
    sa.Column('resolution', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ouvert', 'en_acquisition', 'termine', 'annule', name='scan_session_status'), nullable=False),
    sa.Column('pages_count', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('print_job_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_sessions')
    op.execute('DROP TYPE scan_session_status')
    # ### end Alembic commands ###
